##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  debian:
    # Useful URL: https://github.com/mate-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-mate-team/baul
    - aptitude
    - autoconf-archive
    - autopoint
    - clang
    - clang-tools
    - cppcheck
    - expect #required for unbuffer
    - git
    - gla11y
    - gobject-introspection
    - gtk-doc-tools
    - intltool
    - iso-codes
    - libdconf-dev
    - libexempi-dev
    - libexif-dev
    - libgail-3-dev
    - libgirepository1.0-dev
    - libglib2.0-dev
    - libglib2.0-doc
    - libgtk-3-dev
    - libnotify-dev
    - libpango1.0-dev
    - libselinux1-dev
    - libstartup-notification0-dev
    - libtool
    - libx11-dev
    - libxml2-dev
    - meson
    - python3-lxml
    - quilt
    - shared-mime-info
    - wget
    - xvfb

before_scripts:
  - ./html-cppcheck
  - ./install-from-git https://github.com/mate-desktop/mate-common master
  - ./install-from-git https://github.com/mate-desktop/mate-desktop master

build_scripts:
  - ./before-build
  - ./make-scanbuild '--enable-empty-view --enable-compile-warnings=maximum'
  - ./after-build

after_scripts:
  - ./gen-index -l 20 -i https://github.com/${OWNER_NAME}/cafe-icon-theme/raw/master/cafe/16x16/apps/system-file-manager.png
