##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  debian:
    # Useful URL: https://github.com/mate-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-mate-team/caja
    - aptitude
    - autopoint
    - clang
    - clang-tools
    - cppcheck
    - expect
    - git
    - gla11y
    - gobject-introspection
    - gtk-doc-tools
    - intltool
    - libdconf-dev
    - libexempi-dev
    - libexif-dev
    - libgail-3-dev
    - libgirepository1.0-dev
    - libglib2.0-dev
    - libgtk-3-dev
    - libmate-desktop-dev
    - libnotify-dev
    - libpango1.0-dev
    - libselinux1-dev
    - libstartup-notification0-dev
    - libx11-dev
    - libxml2-dev
    - mate-common
    - python3-lxml
    - quilt
    - shared-mime-info
    - wget
    - xvfb

before_scripts:
  - ./html-cppcheck

build_scripts:
  - ./before-build
  - ./make-scanbuild '--enable-empty-view --enable-compile-warnings=maximum'
  - ./after-build
